name: /Users/scottjg2/Sites/ECO395M/notebooks/env
channels:
  - defaults
dependencies:
  - appnope=0.1.2
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - executing=0.8.3
  - flit-core=3.8.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - future=0.18.3
  - giflib=5.2.1
  - idna=3.4
  - ipykernel=6.19.2
  - ipython=8.12.0
  - jedi=0.18.1
  - joblib=1.1.1
  - jpeg=9e
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nltk=3.7
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1t
  - packaging=23.0
  - pandas=1.5.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=2.5.2
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.10
  - python-dateutil=2.8.2
  - pytorch=1.12.1
  - pytz=2022.7
  - pyyaml=6.0
  - pyzmq=23.2.0
  - readline=8.2
  - regex=2022.7.9
  - requests=2.28.1
  - seaborn=0.12.2
  - setuptools=66.0.0
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tk=8.6.12
  - torchvision=0.13.1
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2023c
  - urllib3=1.26.15
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xz=5.2.10
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
prefix: /Users/scottjg2/Sites/ECO395M/notebooks/env
